[project]
name = "onlain-store"
version = "0.1.0"
description = ""
authors = [
    {name = "Natalia Pochekutova",email = "natalipochekutova51@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django (==4.2.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.lint.dependencies]
black = "^25.1.0"

