# Generated by Django 5.2.3 on 2025-07-13 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ["title"],
                "verbose_name": "статья",
                "verbose_name_plural": "статьи",
            },
        ),
    ]
